// These styles apply to every route in the application
import { Suspense } from "react";
import Footer from "./components/global/footer/index";
import Header from "./components/global/header/index";
import "./globals.css";
import ReduxProvider from "./redux/provider";
import { Toaster } from "./utils/Alert/toas";
import LoadingSpinner from "./components/pages/Loading/LoadingSpinner";

export const metadata = {
  title: "newBareeze",
  icons: {
    icon: "/images/nb-logo-v3.svg",
  },
  description: "Generated by Shams and Company",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <div className="relative">
            <Header />
            <Toaster position="top-center" />
            <Suspense
              fallback={
                <div>
                  <LoadingSpinner />
                </div>
              }
            >
              {children}
            </Suspense>
            <Footer />
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
